// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI-only (migrate, generate, studio) — the running app never reads this
    // config file; PrismaService builds its own pg.Pool from DATABASE_URL
    // directly. Migrations need Neon's DIRECT (non-pooled) connection —
    // PgBouncer's transaction-mode pooling doesn't support the session-level
    // operations `prisma migrate` relies on.
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
