import { PrismaClient } from '@prisma/client';

const muhammadNames = [
  {
    id: 1,
    nameArabic: 'مُحَمَّد',
    nameTranslit: 'Muhammad',
    nameEnglish: 'Muhammad',
    meaning: 'The Praised One',
    description: 'The most commonly used name of the Prophet. It means "the one who is praised and commended."',
  },
  {
    id: 2,
    nameArabic: 'أَحْمَد',
    nameTranslit: 'Ahmad',
    nameEnglish: 'Ahmad',
    meaning: 'The Most Praised',
    description: 'Another name of the Prophet meaning "the most praised one," derived from the same root as Muhammad.',
  },
  {
    id: 3,
    nameArabic: 'الحامِد',
    nameTranslit: 'Al-Hamid',
    nameEnglish: 'The Praised',
    meaning: 'The Praised One',
    description: 'One who praises Allah and is worthy of praise.',
  },
  {
    id: 4,
    nameArabic: 'الحَمِيد',
    nameTranslit: 'Al-Hameed',
    nameEnglish: 'The Most Praiseworthy',
    meaning: 'The Most Praiseworthy',
    description: 'The one who is most praiseworthy and commendable.',
  },
  {
    id: 5,
    nameArabic: 'الماحِي',
    nameTranslit: 'Al-Mahi',
    nameEnglish: 'The Eraser',
    meaning: 'The Eraser of Sins',
    description: 'The one through whom Allah erases the sins of his followers.',
  },
  {
    id: 6,
    nameArabic: 'العاقِب',
    nameTranslit: 'Al-Aqib',
    nameEnglish: 'The Last',
    meaning: 'The Last Prophet',
    description: 'The last and final prophet sent by Allah to mankind.',
  },
  {
    id: 7,
    nameArabic: 'الفاتِح',
    nameTranslit: 'Al-Fatih',
    nameEnglish: 'The Opener',
    meaning: 'The Opener of Victory',
    description: 'The one who opens the doors of victory and guidance for his ummah.',
  },
  {
    id: 8,
    nameArabic: 'النَّبِيّ',
    nameTranslit: 'An-Nabi',
    nameEnglish: 'The Prophet',
    meaning: 'The Prophet',
    description: 'The appointed messenger of Allah to convey His message to mankind.',
  },
  {
    id: 9,
    nameArabic: 'الرَّسول',
    nameTranslit: 'Ar-Rasul',
    nameEnglish: 'The Messenger',
    meaning: 'The Messenger',
    description: 'The one sent by Allah with revelation and guidance.',
  },
  {
    id: 10,
    nameArabic: 'النَّذِير',
    nameTranslit: 'An-Nadhir',
    nameEnglish: 'The Warner',
    meaning: 'The Warner',
    description: 'The one who warns people against Allah\'s punishment.',
  },
  {
    id: 11,
    nameArabic: 'البشِير',
    nameTranslit: 'Al-Bashir',
    nameEnglish: 'The Bearer of Glad Tidings',
    meaning: 'The Bearer of Glad Tidings',
    description: 'The one who brings good news of Paradise to the believers.',
  },
  {
    id: 12,
    nameArabic: 'الداعِي',
    nameTranslit: 'Ad-Dai',
    nameEnglish: 'The Caller',
    meaning: 'The Caller to Allah',
    description: 'The one who calls people to the worship of Allah alone.',
  },
  {
    id: 13,
    nameArabic: 'السِّراج',
    nameTranslit: 'As-Siraj',
    nameEnglish: 'The Lamp',
    meaning: 'The Illuminating Lamp',
    description: 'The one who illuminates the path to Allah like a lamp.',
  },
  {
    id: 14,
    nameArabic: 'المِصباح',
    nameTranslit: 'Al-Misbah',
    nameEnglish: 'The Torch',
    meaning: 'The Torch of Guidance',
    description: 'The one whose guidance is like a torch lighting the way.',
  },
  {
    id: 15,
    nameArabic: 'الهادِي',
    nameTranslit: 'Al-Hadi',
    nameEnglish: 'The Guide',
    meaning: 'The Guide to the Right Path',
    description: 'The one who guides people to the straight path of Allah.',
  },
  {
    id: 16,
    nameArabic: 'التّاهِر',
    nameTranslit: 'At-Tahir',
    nameEnglish: 'The Pure One',
    meaning: 'The Pure',
    description: 'The one who is pure and clean from all impurities and sins.',
  },
  {
    id: 17,
    nameArabic: 'المُطَهَّر',
    nameTranslit: 'Al-Mutahhir',
    nameEnglish: 'The Purifier',
    meaning: 'The Purifier',
    description: 'The one who purifies people from sin and disbelief.',
  },
  {
    id: 18,
    nameArabic: 'طه',
    nameTranslit: 'Taha',
    nameEnglish: 'Taha',
    meaning: 'O Man of Excellence',
    description: 'A name mentioned in the Quran, meaning O man of excellence.',
  },
  {
    id: 19,
    nameArabic: 'يس',
    nameTranslit: 'Yasin',
    nameEnglish: 'Yasin',
    meaning: 'The Wise One',
    description: 'A name of the Prophet mentioned in the Quran, referring to his wisdom.',
  },
  {
    id: 20,
    nameArabic: 'الشّاهِد',
    nameTranslit: 'Ash-Shahid',
    nameEnglish: 'The Witness',
    meaning: 'The Witness',
    description: 'The one who witnessed against all nations on the Day of Judgment.',
  },
  {
    id: 21,
    nameArabic: 'الشَّهيد',
    nameTranslit: 'Ash-Shaheed',
    nameEnglish: 'The Testified',
    meaning: 'The Witnessed',
    description: 'The one testified to by Allah as the truthful messenger.',
  },
  {
    id: 22,
    nameArabic: 'الحاشِر',
    nameTranslit: 'Al-Hashir',
    nameEnglish: 'The Gatherer',
    meaning: 'The Gatherer',
    description: 'The one after whom all people will be gathered on the Day of Judgment.',
  },
  {
    id: 23,
    nameArabic: 'العالِم',
    nameTranslit: 'Al-Alim',
    nameEnglish: 'The Most Knowledgeable',
    meaning: 'The All-Knowing',
    description: 'The one most knowledgeable among all the prophets.',
  },
  {
    id: 24,
    nameArabic: 'المُعَلِّم',
    nameTranslit: 'Al-Mu\'allim',
    nameEnglish: 'The Teacher',
    meaning: 'The Teacher',
    description: 'The one who taught people the knowledge of Allah.',
  },
  {
    id: 25,
    nameArabic: 'البُرهان',
    nameTranslit: 'Al-Burhan',
    nameEnglish: 'The Proof',
    meaning: 'The Clear Proof',
    description: 'The clear proof and evidence of Allah\'s message.',
  },
  {
    id: 26,
    nameArabic: 'المُبِين',
    nameTranslit: 'Al-Mubin',
    nameEnglish: 'The Illustrator',
    meaning: 'The Illustrator',
    description: 'The one who makes clear the message of Allah.',
  },
  {
    id: 27,
    nameArabic: 'الرَّحْمَة',
    nameTranslit: 'Ar-Rahmah',
    nameEnglish: 'The Mercy',
    meaning: 'A Mercy to All Creation',
    description: 'The one sent as a mercy to all of mankind and creation.',
  },
  {
    id: 28,
    nameArabic: 'الرَّحِيم',
    nameTranslit: 'Ar-Rahim',
    nameEnglish: 'The Compassionate',
    meaning: 'The Compassionate One',
    description: 'The compassionate one who showed mercy to the believers.',
  },
  {
    id: 29,
    nameArabic: 'الدّاعِي إلى الله',
    nameTranslit: 'Ad-Dai Ilallah',
    nameEnglish: 'The Caller to Allah',
    meaning: 'The Caller to Allah\'s Way',
    description: 'The one who called people to the straight path of Allah.',
  },
  {
    id: 30,
    nameArabic: 'المُزَكّي',
    nameTranslit: 'Al-Muzkakki',
    nameEnglish: 'The Purifier',
    meaning: 'The Purifier of Souls',
    description: 'The one who purified the souls of believers from impurities.',
  },
  {
    id: 31,
    nameArabic: 'الأمِين',
    nameTranslit: 'Al-Amin',
    nameEnglish: 'The Trustworthy',
    meaning: 'The Trustworthy',
    description: 'Known for his honesty and trustworthiness even before prophethood.',
  },
  {
    id: 32,
    nameArabic: 'الصّادِق',
    nameTranslit: 'As-Sadiq',
    nameEnglish: 'The Truthful',
    meaning: 'The Truthful',
    description: 'The one who always spoke the truth in every matter.',
  },
  {
    id: 33,
    nameArabic: 'الصِّدِّيق',
    nameTranslit: 'As-Siddiq',
    nameEnglish: 'The Affirmer of Truth',
    meaning: 'The Affirmer of Truth',
    description: 'The one confirmed by all believers as truthful.',
  },
  {
    id: 34,
    nameArabic: 'الرّقِيق',
    nameTranslit: 'Ar-Raqiq',
    nameEnglish: 'The Tender-Hearted',
    meaning: 'The Tender-Hearted',
    description: 'The one with a tender and compassionate heart towards believers.',
  },
  {
    id: 35,
    nameArabic: 'الشَّفِيق',
    nameTranslit: 'Ash-Shafiq',
    nameEnglish: 'The Compassionate',
    meaning: 'The Full of Compassion',
    description: 'The one full of compassion and mercy towards his ummah.',
  },
  {
    id: 36,
    nameArabic: 'السِّراج المُنِير',
    nameTranslit: 'As-Siraj Al-Munir',
    nameEnglish: 'The Shining Lamp',
    meaning: 'The Illuminating Lamp',
    description: 'The glowing lamp that illuminates the darkness of ignorance.',
  },
  {
    id: 37,
    nameArabic: 'النّور',
    nameTranslit: 'An-Nur',
    nameEnglish: 'The Light',
    meaning: 'The Light',
    description: 'The light that illuminates the path to Allah.',
  },
  {
    id: 38,
    nameArabic: 'المُنِير',
    nameTranslit: 'Al-Munir',
    nameEnglish: 'The Illuminator',
    meaning: 'The Illuminator',
    description: 'The one who illuminates the hearts with the light of guidance.',
  },
  {
    id: 39,
    nameArabic: 'الأسوَة',
    nameTranslit: 'Al-Uswah',
    nameEnglish: 'The Exemplar',
    meaning: 'The Excellent Example',
    description: 'The perfect model and example for all believers to follow.',
  },
  {
    id: 40,
    nameArabic: 'الأسوَة الحسَنَة',
    nameTranslit: 'Al-Uswah Al-Hasanah',
    nameEnglish: 'The Excellent Exemplar',
    meaning: 'The Excellent Example',
    description: 'The excellent example for all to emulate in conduct.',
  },
  {
    id: 41,
    nameArabic: 'الحافِظ',
    nameTranslit: 'Al-Hafiz',
    nameEnglish: 'The Preserver',
    meaning: 'The Guardian',
    description: 'The one who preserves the message of Allah.',
  },
  {
    id: 42,
    nameArabic: 'المِهْدِي',
    nameTranslit: 'Al-Mahdi',
    nameEnglish: 'The Guided One',
    meaning: 'The Guided One',
    description: 'The one guided to the straight path by Allah.',
  },
  {
    id: 43,
    nameArabic: 'الدّاود',
    nameTranslit: 'Ad-Dawud',
    nameEnglish: 'Like David',
    meaning: 'Similar to Prophet David',
    description: 'The one who, like Prophet David, was strong and mighty.',
  },
  {
    id: 44,
    nameArabic: 'المَلِك',
    nameTranslit: 'Al-Malik',
    nameEnglish: 'The King',
    meaning: 'The Sovereign',
    description: 'The one with sovereignty over the hearts of believers.',
  },
  {
    id: 45,
    nameArabic: 'السَّيِّد',
    nameTranslit: 'As-Sayyid',
    nameEnglish: 'The Master',
    meaning: 'The Master',
    description: 'The master and leader of all creation on the Day of Judgment.',
  },
  {
    id: 46,
    nameArabic: 'القائِم',
    nameTranslit: 'Al-Qai\'m',
    nameEnglish: 'The Standing One',
    meaning: 'The Upright',
    description: 'The one who stands firm in his mission.',
  },
  {
    id: 47,
    nameArabic: 'المُقَدَّم',
    nameTranslit: 'Al-Muqaddim',
    nameEnglish: 'The Exalted',
    meaning: 'The Exalted',
    description: 'The one exalted in rank and status.',
  },
  {
    id: 48,
    nameArabic: 'المُؤَخَّر',
    nameTranslit: 'Al-Mu\'akhkhir',
    nameEnglish: 'The Delayed',
    meaning: 'The Delayed One',
    description: 'The one whose name is mentioned after that of Allah in the testimony.',
  },
  {
    id: 49,
    nameArabic: 'الشَّهِير',
    nameTranslit: 'Ash-Shahir',
    nameEnglish: 'The Famous',
    meaning: 'The Famous',
    description: 'The one whose fame spread throughout the world.',
  },
  {
    id: 50,
    nameArabic: 'الأمّي',
    nameTranslit: 'Al-Ummi',
    nameEnglish: 'The Unlettered',
    meaning: 'The Unlettered',
    description: 'The prophet who could not read or write, yet possessed all knowledge.',
  },
  {
    id: 51,
    nameArabic: 'الكَاتِم',
    nameTranslit: 'Al-Katim',
    nameEnglish: 'The Concealer',
    meaning: 'The One Who Conceals',
    description: 'The one who conceals the faults of others.',
  },
  {
    id: 52,
    nameArabic: 'الطّاهِر',
    nameTranslit: 'At-Tahir',
    nameEnglish: 'The Pure',
    meaning: 'The Pure',
    description: 'The one pure from all evil and impurities.',
  },
  {
    id: 53,
    nameArabic: 'الآخِر',
    nameTranslit: 'Al-Akhir',
    nameEnglish: 'The Last',
    meaning: 'The Last Prophet',
    description: 'The last prophet and messenger sent to all of mankind.',
  },
  {
    id: 54,
    nameArabic: 'الأوَّل',
    nameTranslit: 'Al-Awwal',
    nameEnglish: 'The First',
    meaning: 'The First among Prophets',
    description: 'The first to be called on the Day of Judgment.',
  },
  {
    id: 55,
    nameArabic: 'الوَسِيط',
    nameTranslit: 'Al-Wasit',
    nameEnglish: 'The Intermediary',
    meaning: 'The Intermediary',
    description: 'The intermediary between Allah and His creation.',
  },
  {
    id: 56,
    nameArabic: 'الشَّفِيع',
    nameTranslit: 'Ash-Shafi',
    nameEnglish: 'The Intercessor',
    meaning: 'The Intercessor',
    description: 'The one who intercedes for his ummah on the Day of Judgment.',
  },
  {
    id: 57,
    nameArabic: 'المَشْفُوع',
    nameTranslit: 'Al-Mashfu',
    nameEnglish: 'The One Whose Intercession is Accepted',
    meaning: 'The One Whose Intercession is Accepted',
    description: 'The one whose intercession is accepted by Allah.',
  },
  {
    id: 58,
    nameArabic: 'ذو الحِكْمَة',
    nameTranslit: 'Dhu Al-Hikmah',
    nameEnglish: 'The Possessor of Wisdom',
    meaning: 'The Possessor of Wisdom',
    description: 'The one possessing infinite wisdom from Allah.',
  },
  {
    id: 59,
    nameArabic: 'ذو القُوَّة',
    nameTranslit: 'Dhu Al-Quwwah',
    nameEnglish: 'The Possessor of Strength',
    meaning: 'The Possessor of Strength',
    description: 'The one possessing great strength in matters of faith.',
  },
  {
    id: 60,
    nameArabic: 'العَزِيز',
    nameTranslit: 'Al-Aziz',
    nameEnglish: 'The Mighty',
    meaning: 'The Mighty',
    description: 'The mighty one who conquered hearts.',
  },
  {
    id: 61,
    nameArabic: 'الأمِير',
    nameTranslit: 'Al-Amir',
    nameEnglish: 'The Commander',
    meaning: 'The Commander',
    description: 'The commander of believers and leader of all nations.',
  },
  {
    id: 62,
    nameArabic: 'الحَاكِم',
    nameTranslit: 'Al-Hakim',
    nameEnglish: 'The Judge',
    meaning: 'The Judge',
    description: 'The wise judge whose decisions are based on divine wisdom.',
  },
  {
    id: 63,
    nameArabic: 'العَدْل',
    nameTranslit: 'Al-Adl',
    nameEnglish: 'The Just',
    meaning: 'The Just',
    description: 'The just one who ruled with fairness and equality.',
  },
  {
    id: 64,
    nameArabic: 'الحَليم',
    nameTranslit: 'Al-Halim',
    nameEnglish: 'The Clement',
    meaning: 'The Clement',
    description: 'The forbearing one who was patient and clement.',
  },
  {
    id: 65,
    nameArabic: 'الصَّبور',
    nameTranslit: 'As-Sabur',
    nameEnglish: 'The Patient',
    meaning: 'The Patient',
    description: 'The patient one who endured all hardships with patience.',
  },
  {
    id: 66,
    nameArabic: 'الكَرِيم',
    nameTranslit: 'Al-Karim',
    nameEnglish: 'The Generous',
    meaning: 'The Generous',
    description: 'The generous one who was known for his generosity.',
  },
  {
    id: 67,
    nameArabic: 'الإسْلام',
    nameTranslit: 'Al-Islam',
    nameEnglish: 'Islam',
    meaning: 'Islam',
    description: 'The one through whom Islam was established.',
  },
  {
    id: 68,
    nameArabic: 'المُؤْمِن',
    nameTranslit: 'Al-Mu\'min',
    nameEnglish: 'The Believer',
    meaning: 'The True Believer',
    description: 'The true believer in Allah and His signs.',
  },
  {
    id: 69,
    nameArabic: 'المُسْلِم',
    nameTranslit: 'Al-Muslim',
    nameEnglish: 'The Muslim',
    meaning: 'The Muslim',
    description: 'The one who submitted himself completely to Allah.',
  },
  {
    id: 70,
    nameArabic: 'الحَاشِر',
    nameTranslit: 'Al-Hashir',
    nameEnglish: 'The Gatherer',
    meaning: 'The Gatherer',
    description: 'The one after whom people will be gathered.',
  },
  {
    id: 71,
    nameArabic: 'المُبَشِّر',
    nameTranslit: 'Al-Mubashshir',
    nameEnglish: 'The One Who Gives Glad Tidings',
    meaning: 'The Bearer of Glad Tidings',
    description: 'The one who brought good news to the believers.',
  },
  {
    id: 72,
    nameArabic: 'الاِسْم الأعْظَم',
    nameTranslit: 'Al-Ism Al-A\'zam',
    nameEnglish: 'The Greatest Name',
    meaning: 'The Greatest Name',
    description: 'The one whose greatest name is honored by Allah.',
  },
  {
    id: 73,
    nameArabic: 'المُهْتَدِي',
    nameTranslit: 'Al-Muhtadi',
    nameEnglish: 'The Rightly Guided',
    meaning: 'The Rightly Guided',
    description: 'The one rightly guided by Allah on the straight path.',
  },
  {
    id: 74,
    nameArabic: 'الكَامِل',
    nameTranslit: 'Al-Kamil',
    nameEnglish: 'The Perfect',
    meaning: 'The Perfect',
    description: 'The one with perfect character and complete knowledge.',
  },
  {
    id: 75,
    nameArabic: 'الأقْدَس',
    nameTranslit: 'Al-Aqdas',
    nameEnglish: 'The Most Holy',
    meaning: 'The Most Holy',
    description: 'The most holy and sacred messenger.',
  },
  {
    id: 76,
    nameArabic: 'المُقْتَفِي',
    nameTranslit: 'Al-Muqtafi',
    nameEnglish: 'The Follower',
    meaning: 'The Follower of Truth',
    description: 'The one who followed the truth and guided others to it.',
  },
  {
    id: 77,
    nameArabic: 'الأُسْوَة',
    nameTranslit: 'Al-Uswah',
    nameEnglish: 'The Example',
    meaning: 'The Example',
    description: 'The ultimate example and role model for all believers.',
  },
  {
    id: 78,
    nameArabic: 'المُهَيْمِن',
    nameTranslit: 'Al-Muhaimin',
    nameEnglish: 'The Overseer',
    meaning: 'The Overseer',
    description: 'The overseer and guardian of the trust of Allah.',
  },
  {
    id: 79,
    nameArabic: 'السِّفَارَة',
    nameTranslit: 'As-Sifarah',
    nameEnglish: 'The Messenger',
    meaning: 'The Messenger',
    description: 'The messenger who conveyed the message of Allah.',
  },
  {
    id: 80,
    nameArabic: 'العِصْمَة',
    nameTranslit: 'Al-Isma',
    nameEnglish: 'The Protection',
    meaning: 'The Protected',
    description: 'The one protected by Allah from error in conveying the message.',
  },
  {
    id: 81,
    nameArabic: 'اللَّطِيف',
    nameTranslit: 'Al-Latif',
    nameEnglish: 'The Subtle',
    meaning: 'The Subtle',
    description: 'The subtle one in achieving his goals and purposes.',
  },
  {
    id: 82,
    nameArabic: 'الرَّفِيق',
    nameTranslit: 'Ar-Rafiq',
    nameEnglish: 'The Companion',
    meaning: 'The Companion',
    description: 'The gentle and kind companion to believers.',
  },
  {
    id: 83,
    nameArabic: 'الوِدود',
    nameTranslit: 'Al-Wadud',
    nameEnglish: 'The Loving',
    meaning: 'The Loving',
    description: 'The one loved by Allah and who showed love to his ummah.',
  },
  {
    id: 84,
    nameArabic: 'النّاصِح',
    nameTranslit: 'An-Nasih',
    nameEnglish: 'The Sincere Adviser',
    meaning: 'The Sincere Adviser',
    description: 'The sincere adviser who gave honest counsel to his ummah.',
  },
  {
    id: 85,
    nameArabic: 'المُحَدِّث',
    nameTranslit: 'Al-Muhadith',
    nameEnglish: 'The Inspired',
    meaning: 'The Inspired',
    description: 'The one inspired by Allah with knowledge and wisdom.',
  },
  {
    id: 86,
    nameArabic: 'الرُّوح',
    nameTranslit: 'Ar-Ruh',
    nameEnglish: 'The Spirit',
    meaning: 'The Spirit',
    description: 'The spirit and essence of all guidance.',
  },
  {
    id: 87,
    nameArabic: 'الشَّافِعُ',
    nameTranslit: 'Ash-Shafi',
    nameEnglish: 'The Intercessor',
    meaning: 'The Intercessor',
    description: 'The one whose intercession is sought on the Day of Judgment.',
  },
  {
    id: 88,
    nameArabic: 'الثَّقَفِي',
    nameTranslit: 'At-Thaqafi',
    nameEnglish: 'The Quick-Witted',
    meaning: 'The Quick-Witted',
    description: 'The quick-witted one in matters of faith.',
  },
  {
    id: 89,
    nameArabic: 'الإمام',
    nameTranslit: 'Al-Imam',
    nameEnglish: 'The Leader',
    meaning: 'The Leader',
    description: 'The leader and guide of all believers.',
  },
  {
    id: 90,
    nameArabic: 'الدّاعِي إلى سَبِيلِ رَبِّه',
    nameTranslit: 'Ad-Dai Ila Sabili Rabbih',
    nameEnglish: 'The Caller to Allah\'s Path',
    meaning: 'The Caller to the Path of His Lord',
    description: 'The one who called to the path of Allah with wisdom.',
  },
  {
    id: 91,
    nameArabic: 'المُنْقِذ',
    nameTranslit: 'Al-Munqidh',
    nameEnglish: 'The Rescuer',
    meaning: 'The Rescuer',
    description: 'The one who rescued people from the darkness of ignorance.',
  },
  {
    id: 92,
    nameArabic: 'المُحَرَّر',
    nameTranslit: 'Al-Muharrir',
    nameEnglish: 'The Liberator',
    meaning: 'The Liberator',
    description: 'The one who liberated people from falsehood.',
  },
  {
    id: 93,
    nameArabic: 'المُعْتَصِم',
    nameTranslit: 'Al-Mu\'tasim',
    nameEnglish: 'The Firm',
    meaning: 'The Firm',
    description: 'The firm one who held fast to Allah\'s guidance.',
  },
  {
    id: 94,
    nameArabic: 'الأَمِير المُؤْمِنِين',
    nameTranslit: 'Amir Al-Mumineen',
    nameEnglish: 'The Commander of the Believers',
    meaning: 'The Commander of the Believers',
    description: 'The commander and leader of all believers.',
  },
  {
    id: 95,
    nameArabic: 'خَاتَم النَّبِيِّين',
    nameTranslit: 'Khatam An-Nabiyeen',
    nameEnglish: 'The Seal of the Prophets',
    meaning: 'The Seal of the Prophets',
    description: 'The last and final prophet, sealing the line of prophethood.',
  },
  {
    id: 96,
    nameArabic: 'شَاهِد مُبِين',
    nameTranslit: 'Shahid Mubin',
    nameEnglish: 'A Clear Witness',
    meaning: 'A Clear Witness',
    description: 'A clear witness to the truth of the message of Allah.',
  },
  {
    id: 97,
    nameArabic: 'بَشِير وَنَذِير',
    nameTranslit: 'Bashir wa Nadhir',
    nameEnglish: 'Bearer of Glad Tidings and Warner',
    meaning: 'Bearer of Glad Tidings and Warner',
    description: 'The one who brought good news and warning to mankind.',
  },
  {
    id: 98,
    nameArabic: 'الرَّحْمَة المُرْسَلَة',
    nameTranslit: 'Ar-Rahmah Al-Mursal',
    nameEnglish: 'The Mercy Sent',
    meaning: 'The Mercy Sent to All Worlds',
    description: 'The mercy that was sent as a blessing to all creation.',
  },
  {
    id: 99,
    nameArabic: 'مُحَمَّد رَسُول الله',
    nameTranslit: 'Muhammad Rasul Allah',
    nameEnglish: 'Muhammad the Messenger of Allah',
    meaning: 'Muhammad, the Messenger of Allah',
    description: 'The complete title of the Prophet, Muhammad, the Messenger of Allah.',
  },
];

export async function seedMuhammadNames(prisma: PrismaClient) {
  try {
    for (const name of muhammadNames) {
      await prisma.muhammadName.upsert({
        where: { id: name.id },
        update: name,
        create: name,
      });
    }
    console.log('✅ Successfully seeded 99 Names of Muhammad (saw)');
  } catch (error) {
    console.error('❌ Error seeding Muhammad names:', error);
    throw error;
  }
}
